apiVersion: gitisking/v1
version: v2.1.0
env: dev
metadata:
  name: restock-service
  version: v2.1.0
  repo: https://github.com/ARAldhafeeri/restock-service-config.git
  language: nodejs
  devBaseURL: https://localhost:3000/restock/dev/
  stageBaseURL: https://localhost:3000/restock/stage/
  prodBaseURL: https://localhost:3000/restock/prod/
  description: "Manages the restocking process for products when stock falls below a threshold."
actualState:
  handshake:
    lastChecked: "2024-09-23T12:00:00Z"
    handshakeStatus: successful
    details:
      stockService:
        status: true
        message: "Handshake successful with stock Service"
      pricingService:
        status: true
        message: "Handshake successful with pricing Service"
desiredState:
  stockService:
    sync: strict
    repo: https://github.com/ARAldhafeeri/stock-service-config.git
  pricingService:
    sync: strict
    repo: https://github.com/ARAldhafeeri/pricing-service-config.git